# Technical Task - Khouloud ISSA

# Exercices

## 1) Create and one-dimensional array ‘a’ containing values: ‘1,2,3,4,5,6,7,8’ and print the number of dimensions in this array using built-in Numpy functionality.

In [7]:
import numpy as np
a = np.arange(1,9,1)
print('shape:',a.shape)
print('a=',a)
print('number of dimensions is',a.ndim,'D')

shape: (8,)
a= [1 2 3 4 5 6 7 8]
number of dimensions is 1 D


## 2) Replace all odd numbers in ‘a’ with ‘-1’ Input.

In [8]:
# a number is odd when the remainder of its devision by 2 is 1
odd_numbers = (np.remainder(a,2)==1)
a[odd_numbers] = -1
print('a=',a)

a= [-1  2 -1  4 -1  6 -1  8]


## 3) Add two empty dimensions to the array ‘a’ using Numpy functionality.

In [9]:
b = np.expand_dims(a,(0,1))
print('shape:',b.shape)
print('b=',b)
print(b.ndim,'D dimensions')

shape: (1, 1, 8)
b= [[[-1  2 -1  4 -1  6 -1  8]]]
3 D dimensions


## 4) Copy existing values into one of the unused empty dimensions, such that only one empty dimension remains.

In [10]:
c = np.insert(b, 0, a, axis=0)
print('shape:',c.shape)
print('c=',c)
print(c.ndim,'D dimensions')

shape: (2, 1, 8)
c= [[[-1  2 -1  4 -1  6 -1  8]]

 [[-1  2 -1  4 -1  6 -1  8]]]
3 D dimensions


## 5) Remove all the unused dimensions.

In [11]:
d = np.squeeze(c,1)
print(d.shape)
print(d)
print(d.ndim,'D dimensions')

(2, 8)
[[-1  2 -1  4 -1  6 -1  8]
 [-1  2 -1  4 -1  6 -1  8]]
2 D dimensions
